name: image_caption_app
description: A Flutter app for image captioning with ML Kit and gallery management.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  image_picker: ^1.0.7
  google_mlkit_image_labeling: ^0.14.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For assets (if any)
# assets:
#   - assets/

flutter:
  uses-material-design: true
